version: '3'

services:
        wordpressdb:
                image: mysql:5.7
                volumes:
                        - mysql_storage_wpdb:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_USER: rafia
                        MYSQL_PASSWORD: rafia
                        MYSQL_DATABASE: mydb


        wordpressos:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on:
                        - wordpressdb
                ports:
                    - 8080:80
                environment:
                        WORDPRESS_DB_HOST: wordpressdb
                        WORDPRESS_DB_USER: rafia        
                        WORDPRESS_DB_PASSWORD: rafia
                        WORDPRESS_DB_NAME: mydb
                volumes:
                        - wpos_storage:/var/www/html
volumes:
        wpos_storage:
        mysql_storage_wpdb:
